version: "3.9"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordgame
    volumes:
      - db-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

volumes:
  db-data:
