type Game {
  id: ID!
  letters: String!
  correct: [String!]!
  incorrect: [String!]!
  total: Int!
}

type GuessResult {
  correct: Boolean!
  word: String!
  game: Game!
}

type Query {
  game(id: ID!): Game!
}

type Mutation {
  createGame: Game!
  addGuess(guess: String!): GuessResult!
}

type Subscription {
  watchGame: GuessResult!
}
