// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Game struct {
	ID        string   `json:"id"`
	Letters   string   `json:"letters"`
	Correct   []string `json:"correct"`
	Incorrect []string `json:"incorrect"`
	Total     int      `json:"total"`
}

type GuessResult struct {
	Correct bool   `json:"correct"`
	Word    string `json:"word"`
	Game    *Game  `json:"game"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
